### ISSUE TITLE
Catberry 9.0 readiness checklist

### ISSUE THREAD

**Issue by pragmader** [catberry/catberry#327]
## Core modules

- [x] `catberry-locator` https://github.com/catberry/catberry-locator/pull/5
  - [x] update all dependencies to their last versions
  - [x] change node versions in the Travis config file to 6, 7

- [x] `catberry-uhr` https://github.com/catberry/catberry-uhr/pull/19
  - [x] update all dependencies to their last versions
  - [x] change node versions in the Travis config file to 6, 7

- [x] `catberry-uri` https://github.com/catberry/catberry-uri/pull/18
  - [x] update all dependencies to their last versions
  - [x] change node versions in the Travis config file to 6, 7

### Main plugins

- [x] `catberry-logger` https://github.com/catberry/catberry-logger/pull/1
  - [x] switch to the [new event names](https://github.com/catberry/catberry/pull/320).
  - [x] add peer dependency for `"catberry": "^9.0.0"`
  - [x] change the supported engine to `>=6.10.0`
  - [x] change node versions in the Travis config file to 6, 7
  - [x] update all dependencies to their last versions

- [x] `catberry-l10n` https://github.com/catberry/catberry-l10n/pull/20
  - [x] add peer dependency for `"catberry": "^9.0.0"`
  - [x] change the supported engine to `>=6.10.0`
  - [x] update all dependencies to their last versions
  - [x] change node versions in the Travis config file to 6, 7

- [x] `catberry-oauth2-client` https://github.com/catberry/catberry-oauth2-client/pull/10
  - [x] add peer dependency for `"catberry": "^9.0.0"`
  - [x] update all dependencies to their last versions
  - [x] add node versions to the Travis config file: 6, 7

- [x] `catberry-assets` https://github.com/catberry/catberry-assets/pull/19
  - [x] add `^9.0.0` to catberry in `peerDependencies`
  - [x] update dependencies to their last versions
  - [x] add node versions to the Travis config file: 6, 7

- [x] `catberry-socket.io` https://github.com/catberry/catberry-socket.io/pull/4
  - [x] add `^9.0.0` to catberry in `peerDependencies`
  - [x] update dependencies to their last versions
  - [x] add node versions to the Travis config file: 6, 7

- [x] `catberry-handlebars` https://github.com/catberry/catberry-handlebars/pull/7
  - [x] add `^9.0.0` to catberry in `peerDependencies`
  - [x] update dependencies to their last versions
  - [x] Implement new required methods https://github.com/catberry/catberry/issues/245
  - [x] add node versions to the Travis config file: 6, 7

- [x] `catberry-pug` https://github.com/catberry/catberry-pug/pull/1
  - [x] add `^9.0.0` to catberry in `peerDependencies`
  - [x] update dependencies to their last versions
  - [x] Implement new required methods https://github.com/catberry/catberry/issues/245
  - [x] add node versions to the Travis config file: 6, 7

- [x] `catberry-dust` https://github.com/catberry/catberry-dust/pull/7
  - [x] add `^9.0.0` to catberry in `peerDependencies`
  - [x] update dependencies to their last versions
  - [x] Implement new required methods https://github.com/catberry/catberry/issues/245
  - [x] add node versions to the Travis config file: 6, 7

### Additional plugins (depend on main ones)

- [x] `catberry-l10n-handlebars-helper` https://github.com/catberry/catberry-l10n-handlebars-helper/pull/5
  - [x] add peer dependency for `"catberry": "^9.0.0"`
  - [x] update peer dependency for `catberry-handlebars`
  - [x] set new version of `catberry-l10n` as a peer dependency
  - [x] update all dependencies to their last versions
  - [x] add node versions to the Travis config file: 6, 7

- [x] `catberry-l10n-dust-helper` https://github.com/catberry/catberry-l10n-dust-helper/pull/3
  - [x] add peer dependency for `"catberry": "^9.0.0"`
  - [x] update peer dependency for `catberry-dust`
  - [x] set new version of `catberry-l10n` as a peer dependency
  - [x] update all dependencies to their last versions
  - [x] add node versions to the Travis config file: 6, 7

## Tools

- [x] `catberry-cli` (has to be released at the same time with Catberry 9)
https://github.com/catberry/catberry-cli/pull/22
  - [x] update `empty-dust` template to use new logger, catberry and engine
  - [x] update `empty-handlebars` to use new logger, catberry and engine
  - [x] create `empty-pug` instead of `empty-jade`
  - [x] update `example` template to use new logger, catberry and engine. Update Travis config.
  - [x] change the supported engine to `>=6.10.0`
  - [x] add node versions to the Travis config file: 6, 7

- [ ] `generator-catberry` (has to be released after catberry-cli) https://github.com/catberry/generator-catberry/pull/15
  - [x] update template submodules to the last versions after changes in `catberry-cli`
  - [x] replace `jade` with `pug`

- [x] `catberry-debugger` https://github.com/catberry/catberry-debugger/pull/15
  - [x] update dependencies to their last versions

## Apps migration (after Catberry 9.0 released)

- [x] `catberry-todomvc` https://github.com/catberry/catberry-todomvc/pull/27
  - [x] change script tags in the document's head element
  - [x] change the `catberry version` in package.json to `^9.0.0`
  - [x] change the `catberry-logger` version to `^2.0.0`
  - [x] change supported node version to `>=6.10.0`
  - [x] change node version in the Travis config file to 6, 7
  - [x] update dependencies to their last versions
  - [x] update .gitignore changing `__BrowserBundle.js` to `.appDefinitions.js`

- [x] `catberry-homepage` https://github.com/catberry/catberry-homepage/pull/36
  - [x] change script tags in the document's head element
  - [x] change the `catberry version` in package.json to `^9.0.0`
  - [x] change the `catberry-logger` version to `^2.0.0`
  - [x] change supported node version to `>=6.10.0`
  - [x] change node version in the Travis config file to 6, 7
  - [x] update dependencies to their last versions
  - [x] update .gitignore changing `__BrowserBundle.js` to `.appDefinitions.js`

- [x] `catberry-example` https://github.com/catberry/catberry-example/pull/12
  - [x] change script tags in the document's head element
  - [x] change the `catberry version` in package.json to `^9.0.0`
  - [x] change the `catberry-logger` version to `^2.0.0`
  - [x] change supported node version to `>=6.10.0`
  - [x] change node version in the Travis config file to 6, 7
  - [x] update dependencies to their last versions
  - [x] update .gitignore changing `__BrowserBundle.js` to `.appDefinitions.js`

**Comment by pragmader** [comment]
Seems like nobody can publish the new NPM package for https://github.com/catberry/generator-catberry except @ptz. So, I'm closing the issue because the rest of it is done.
