### ISSUE TITLE
Catberry 9 testing checklist

### ISSUE THREAD

**Issue by pragmader** [catberry/catberry#335]
- [x] previous projects work without errors after migrating to the new split bundle
- [x] catberry CLI
  - [x] all templates are generated correctly, then `npm i --production`, `npm run debug` and `npm start` produce no error
  - [x] all running template websites render a proper layout and produce no error on the console
  - [x] a new component is added to the a correctly
  - [x] a new store is added to a project correctly
- [x] Works on Linux
- [x] Works on Mac (@chetverikov experiences some problems with native modules)
- [x] Works on Windows
- [x] Works on IE 11

**Comment by pragmader** [comment]
Tested with `catberry-homepage` on Linux and Mac.

**Comment by pragmader** [comment]
I'll be testing CLI soon.

**Comment by pragmader** [comment]
@chetverikov I think you have the similar problem https://github.com/nodejs/node/issues/9370

**Comment by kalyanov** [comment]
I have started flamp.ru app on windows 10 with debug-win command.

I have checked the following scenarios in browsers chrome 56, IE11 and Edge:
1. Login/Logout
2. Company search and sorting
3. Writing a review (text writing and image uploading)
4. Messages sending 

There were no bugs :)
